### ISSUE TITLE
action has started to fail because of github countermeasures

### ISSUE THREAD

**Issue by fredrikhgrelland** [alstr/todo-to-issue-action#248]
```
Traceback (most recent call last):
  File "/app/main.py", line 933, in <module>
    raw_issues = TodoParser().parse(last_diff)
                 ^^^^^^^^^^^^
  File "/app/main.py", line 441, in __init__
    raise Exception('Cannot retrieve languages data. Operation will abort.')
Exception: Cannot retrieve languages data. Operation will abort.
```
context: https://github.com/readthedocs/readthedocs.org/issues/11763#issuecomment-2477034172

**Comment by alstr** [comment]
Thanks for the report! I'll roll out a new release now, let me know if that solves things.

**Comment by alstr** [comment]
Thanks for the heads up.
