### ISSUE TITLE
Action fails unable to retrieve diff

### ISSUE THREAD

**Issue by nkakouros** [alstr/todo-to-issue-action#42]
[Here](https://github.com/nkakouros-original/ansible-role-beats/blob/master/.github/workflows/todo-issuer.yml) is the workflow I am trying to setup. I have enabled the todo-to-issue-action step, but it fails with:

```
Run alstr/todo-to-issue-action@v3.0.1-beta
  with:
    CLOSE_ISSUES: true
    AUTO_P: false
    REPO: nkakouros-original/ansible-role-beats
    BEFORE: c9c7e1242971abbee4aa8defb3183985616f63c4
    SHA: dbbda01ee1b9e9bf4f2404ddfe9057a4fb8954da
/usr/bin/docker run --name e4135e4d2de8b243f1ae8a9075ac589e25_9935fc --label 5588e4 --workdir /github/workspace --rm -e INPUT_CLOSE_ISSUES -e INPUT_AUTO_P -e INPUT_REPO -e INPUT_BEFORE -e INPUT_SHA -e INPUT_TOKEN -e INPUT_LABEL -e INPUT_COMMENT_MARKER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ansible-role-beats/ansible-role-beats":"/github/workspace" 5588e4:135e4d2de8b243f1ae8a9075ac589e25
Traceback (most recent call last):
  File "/app/main.py", line 454, in <module>
    last_diff = StringIO(client.get_last_diff())
  File "/app/main.py", line 68, in get_last_diff
    raise Exception('Could not retrieve diff. Operation will abort.')
Exception: Could not retrieve diff. Operation will abort.
```

What am I doing wrong?

**Comment by nkakouros** [comment]
OK, I had to set `TOKEN: ${{ secrets.GITHUB_TOKEN }}`. The reason I didn't do so in the first place was the comment:

```
The GitHub access token to allow us to retrieve, create and update issues (automatically set)
```

I understood it as, hey you don't need to set this to anything.
