### ISSUE TITLE
TODO comments for TeX

### ISSUE THREAD

**Issue by qwinters** [alstr/todo-to-issue-action#95]
TODO comments for TeX appear to be broken. 

For example of a failed run action run, see commit: https://github.com/qwinters/course-repo-template/commit/bb15f68d974b81d542c22c9c7c450d429635815c 

Full error stack trace from actions view: 
```shell 
/usr/bin/docker run --name ghcrioalstrtodotoissueactionv45_95d841 --label 6a6825 --workdir /github/workspace --rm -e INPUT_AUTO_ASSIGN -e INPUT_REPO -e INPUT_BEFORE -e INPUT_COMMITS -e INPUT_DIFF_URL -e INPUT_SHA -e INPUT_TOKEN -e INPUT_LABEL -e INPUT_COMMENT_MARKER -e INPUT_CLOSE_ISSUES -e INPUT_AUTO_P -e INPUT_PROJECTS_SECRET -e INPUT_USER_PROJECTS -e INPUT_ORG_PROJECTS -e INPUT_IGNORE -e INPUT_ACTOR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/course-repo-template/course-repo-template":"/github/workspace" ghcr.io/alstr/todo-to-issue-action:v4.5
Traceback (most recent call last):
  File "/app/main.py", line 633, in <module>
    raw_issues = TodoParser().parse(last_diff)
  File "/app/main.py", line 425, in parse
    comments = re.finditer(comment_pattern, block['hunk'], re.DOTALL)
  File "/usr/lib/python3.7/re.py", line 230, in finditer
    return _compile(pattern, flags).finditer(string)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 816, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.7/sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \e at position 31
```

**Comment by qwinters** [comment]
Update: did a little bit of digging through things in my example repo (and the other repos where this was failing) and I'm not quite sure where the issues would be coming from because the diffs where things failed did not include any `\e`. 

Looking closer at the error message, it looks like the `\\e` bad escape is coming from compiling the pattern, which I think means that the actual pattern itself has an error. Specifically, I think this is coming from the syntax.json for `\\end{comment}`. 

I'll try to submit a PR to fix this up (along with a LaTeX test)

**Comment by alstr** [comment]
I may have come across a similar issue a while back, whereby already escaped strings were causing a bad escape error, so this has been on my radar but thanks very much for giving it some attention.

**Comment by alstr** [comment]
Thanks for spotting and fixing this. Long-term I am thinking about removing the escaping from `syntax.json` and applying it when the action runs instead.
